spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/notification_service
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update

  config:
    name: notification-service
    import: optional:configserver:http://localhost:8888

  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: guest
  #    password: guest
  #
  #  cloud:
  #    bus:
  #      trace:
  #        enabled: true

  kafka:
    bootstrap-servers: localhost:9094


api-gateway:
  url: http://localhost:9191

firebase:
  service-account: "src/main/resources/service-account.json"
