spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/notification_service
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update

  config:
    name: notification-service
    import: optional:configserver:http://config-server:8888

#  rabbitmq:
#    host: rabbitmq
#    port: 5672
#    username: guest
#    password: guest
#
#  cloud:
#    bus:
#      trace:
#        enabled: true

  kafka:
    bootstrap-servers: kafka:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      weight: 50
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/

api-gateway:
  url: http://api-gateway:9191

firebase:
  service-account: "src/main/resources/service-account.json"