server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: IDENTITY-SERVICE
  profiles:
#    active: test
    active: @spring.profiles.active@

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  observations:
    http:
      server:
        requests:
          name: http.server.requests
  # Thêm tag chứa context path vào tất cả metrics
  metrics:
    tags:
      context-path: ${server.servlet.context-path}
      application: ${spring.application.name}

  tracing:
    sampling:
      probability: 1.0 # 100% request được tracking (nếu hệ thống lớn, có thể giảm xuống 0.5)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html