server:
  host: "0.0.0.0"
  port: 5601

elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "Duc021003@"
  ssl:
    verificationMode: none

xpack:
  security:
    enabled: true
    encryptionKey: "lekhanhduc021020003a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t"
  encryptedSavedObjects:
    encryptionKey: "lekhanhduc0210200039f7e5d2a48bc9d1e2f3A4b5c6d7e8f9a0b1c2d3"
  reporting:
    encryptionKey: "lekhanhduc0210200037t9s8r76p5o4n3m2l1k0j9i8h7g6f5e4d3c2b1a"