global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "identity-service"
    metrics_path: '/identity/actuator/prometheus'
    static_configs:
      - targets: ["host.docker.internal:8080"]
#     - targets: ['${IDENTITY_SERVICE_HOST:-host.docker.internal}:8080']
        labels:
          application: 'IDENTITY-SERVICE'

  - job_name: "notification-service"
    metrics_path: '/notification/actuator/prometheus'
    static_configs:
      - targets: ["host.docker.internal:8082"]
#      - targets: ['${NOTIFICATION_SERVICE_HOST:-host.docker.internal}:8082']
        labels:
          application: 'NOTIFICATION-SERVICE'

  - job_name: "profile-service"
    metrics_path: '/profile/actuator/prometheus'
    static_configs:
      - targets: ["host.docker.internal:8081"]
#      - targets: ['${PROFILE_SERVICE_HOST:-host.docker.internal}:8081']
        labels:
          application: 'PROFILE-SERVICE'

