spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 550MB
  config:
    name: course-service
    import: optional:configserver:http://config-server:8888

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/course_service
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka:9092

  elasticsearch:
    host: elasticsearch
    port: 9200
    username: root
    password: 123456

api-gateway:
  url: http://api-gateway:9191

minio:
  bucket-name: course-application

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      weight: 50
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/