pipeline {
	agent any
    tools {
		jdk 'JDK21'
        maven 'Maven-3.9.9'
    }
    environment {
		GITHUB_TOKEN = credentials('github-token')
        SONAR_TOKEN = credentials('sonar-token')
        SLACK_WEBHOOK_URL = credentials('slack-webhook-url')
    }
    stages {
		stage('Checkout Code') {
			steps {
				script {
					if (fileExists('ElearningPlatform')) {
						echo 'Repository already exists. Pulling latest changes...'
                        dir('ElearningPlatform') {
							sh 'git reset --hard'
                            sh 'git pull origin master'
                        }
                    } else {
						echo 'Cloning repository...'
                        withCredentials([usernamePassword(credentialsId: 'github-token', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_TOKEN')]) {
							sh "git clone https://${GIT_USERNAME}:${GIT_TOKEN}@github.com/lekhanhduc/ElearningPlatform.git"
                        }
                    }
                }
            }
        }
        stage('Build IdentityService') {
			steps {
				dir('ElearningPlatform/identity-service') {
					withEnv(["JAVA_HOME=${tool 'JDK21'}"]) {
					    sh 'echo $JAVA_HOME'
                        sh 'java -version'
						sh 'mvn clean install -DskipTests'
                    }
                }
            }
        }
        stage('Code Quality With SonarQube') {
			steps {
				echo 'Running SonarQube analysis for IdentityService...'
                dir('BookStorePlatform/identity-service') {
					sh """
                        mvn sonar:sonar \
                            -Dsonar.projectKey=identity-service \
                            -Dsonar.projectName=identity-service \
                            -Dsonar.host.url=http://sonarqube:9000 \
                            -Dsonar.login=${SONAR_TOKEN}
                    """
                }
            }
        }
        stage('Build Package') {
			steps {
				dir('ElearningPlatform/identity-service') {
					sh 'mvn package -DskipTests'
                }
            }
        }
        stage('Archive Artifact') {
			steps {
				archiveArtifacts artifacts: 'ElearningPlatform/identity-service/target/*.jar', fingerprint: true
            }
        }
        stage('Build Docker Image') {
			steps {
				dir('ElearningPlatform/identity-service') {
					sh "docker build -t identity-service:1.0.0 ."
                    sh "docker tag identity-service:1.0.0 khanhduc/identity-service:1.0.0"
                }
            }
        }
        stage('Push Docker Image') {
            steps {
				dir('ElearningPlatform/identity-service') {
					sh "docker push khanhduc/identity-service:1.0.0"
                }
            }
        }

    }
    post {
		success {
			echo 'Pipeline completed successfully!'
            script {
				withCredentials([string(credentialsId: 'slack-webhook-url', variable: 'WEBHOOK')]) {
					sh '''
                        curl -X POST -H 'Content-type: application/json' --data '{
                            "text": "✅ *Pipeline Success* | *IdentityService* \\n- Version: 1.0.0 \\n- Job: '"${JOB_NAME}"' \\n- Build: #'"${BUILD_NUMBER}"' \\n- URL: '"${BUILD_URL}"'"
                        }' ${WEBHOOK}
                    '''
                }
            }
        }
        failure {
			echo 'Pipeline failed!'
            script {
				withCredentials([string(credentialsId: 'slack-webhook-url', variable: 'WEBHOOK')]) {
					sh '''
                        curl -X POST -H 'Content-type: application/json' --data '{
                            "text": "❌ *Pipeline Failed* | *IdentityService* \\n- Job: '"${JOB_NAME}"' \\n- Build: #'"${BUILD_NUMBER}"' \\n- URL: '"${BUILD_URL}"'"
                        }' ${WEBHOOK}
                    '''
                }
            }
        }
        always {
			cleanWs()
        }
    }

}
