spring:
  config:
    import: optional:configserver:http://localhost:8888
    name: payment-service

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/payment_service
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9094


resilience4j.circuitbreaker:
  instances:
    PAYMENT-SERVICE:
      slidingWindowSize: 10       # Số lượng yêu cầu để tính toán tỷ lệ lỗi
      failureRateThreshold: 50       # Tỷ lệ lỗi (%) để mở Circuit Breaker
      waitDurationInOpenState: 10000 # Thời gian chờ trước khi chuyển sang trạng thái nửa mở (ms)
      permittedNumberOfCallsInHalfOpenState: 3  # Số lượng yêu cầu cho phép ở trạng thái nửa mở
      slidingWindowType: COUNT_BASED # Loại cửa sổ (dựa trên số lượng yêu cầu)
      minimumNumberOfCalls: 5        # Số lượng yêu cầu tối thiểu để kích hoạt tính toán lỗi
      automatic-transition-from-open-to-half-open-enabled: true
