spring:
  config:
    import: optional:configserver:http://localhost:8888
    name: payment-service

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/payment_service
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9094

PAYOS_CLIENT_ID:
PAYOS_API_KEY:
PAYOS_CHECKSUM_KEY: