spring:
  config:
    import: optional:configserver:http://config-server:8888
    name: payment-service

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://postgres:5432/payment_service
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka:9092

PAYOS_CLIENT_ID: ${PAYOS_CLIENT_ID}
PAYOS_API_KEY: ${PAYOS_API_KEY}
PAYOS_CHECKSUM_KEY: ${PAYOS_CHECKSUM_KEY}
