spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 550MB
  data:
    mongodb:
      uri: mongodb://root:root@mongodb:27017/notification-service?authSource=admin
  #      username: root
  #      password: 123456

  config:
    import: optional:configserver:http://config-server:8888
    name: file-service

#  rabbitmq:
#    host: rabbitmq
#    port: 5672
#    username: guest
#    password: guest
#
#  cloud:
#    bus:
#      trace:
#        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      weight: 50
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/

file:
  storage-dir: C:/upload
  download-prefix: http://localhost:9191/file/download/

minio:
  endpoint-url: ${MINIO_DOMAIN}
  access-key: minioadmin
  secret-key: 12345678
