spring:
  application:
    name: IDENTITY-SERVICE
  boot:
    message: Hello, Identity Service, Spring Cloud Bus (Test Environment)

  config:
    import: optional:configserver:http://config-server:8888

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123456}
    url: jdbc:postgresql://${DATABASE_HOST:postgres}:${DATABASE_PORT:5433}/identity_service

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 441587123979-qds882ebt12bna4t4pldj9ausd2udpu2.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
            redirect-uri: http://localhost:4200/oauth2/callback/google
          github:
            client-id: Ov23liYKvBAfzCvqcWfE
            client-secret: 4f3ab5c44757ab662c66ab305c505031448e974b
            scope: user,user:email
            redirect-uri: http://localhost:4200/oauth2/callback/github
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

  data:
    redis:
      port: 6379
      host: ${SPRING_DATA_REDIS_HOST:redis}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://registry-service:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org.springframework.cloud.config: DEBUG
    com.netflix.discovery: DEBUG

jwt:
  secret-key: ${JWT_SECRET_KEY}

resilience4j:
  circuitbreaker:
    instances:
      IDENTITY-SERVICE:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 4000ms
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5000ms
  retry:
    instances:
      IDENTITY-SERVICE:
        maxAttempts: 3
        waitDuration: 1000ms
  ratelimiter:
    instances:
      identityService:
        limitForPeriod: 500
        limitRefreshPeriod: 1s
        timeoutDuration: 500ms

sub-domain: ${SUB_DOMAIN}

google:
  client-id: 441587123979-qds882ebt12bna4t4pldj9ausd2udpu2.apps.googleusercontent.com
  secret-key: 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
  redirect-uri: http://localhost:4200/oauth2/callback/google