spring:
  config:
    import: optional:configserver:http://config-server:8888
    name: profile-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/profile_service
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9092

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

#  tracing:
#    sampling:
#      probability: 1.0 # 100% request được tracking (nếu hệ thống lớn, có thể giảm xuống 0.5)
#  zipkin:
#    tracing:
#      endpoint: http://zipkin:9411/api/v2/spans

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      weight: 50
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/
---


aws:
  s3:
    bucket-name: bookstore-application
    endpoint-url: http://minio:9002
  credentials:
    access-key: minioadmin
    secret-key: 12345678

spring:
  boot:
    message: Hello Profile Service, Spring Cloud Bus

api-gateway:
  url: http://api-gateway:9191
