spring:
  config:
    name: order-service
    import: optional:configserver:http://config-server:8888

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://postgres:5432/order_service
  jpa:
    hibernate:
      ddl-auto: update

  #  rabbitmq:
  #    host: rabbitmq
  #    port: 5672
  #    username: guest
  #    password: guest
  #
  #  cloud:
  #    bus:
  #      trace:
  #        enabled: true

  kafka:
    bootstrap-servers: kafka:9092

resilience4j:
  circuitbreaker:
    instances:
      PAYMENT-SERVICE:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      PAYMENT-SERVICE:
        max-attempts: 3
        waitDuration: 500
  timelimiter:
    instances:
      PAYMENT-SERVICE:
        timeoutDuration: 5s