spring:
  config:
    import: optional:configserver:http://localhost:8888
    name: order-service

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/order_service
  jpa:
    hibernate:
      ddl-auto: update

  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: guest
  #    password: guest
  #
  #  cloud:
  #    bus:
  #      trace:
  #        enabled: true

  kafka:
    bootstrap-servers: localhost:9094

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    instances:
      PAYMENT-SERVICE:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      PAYMENT-SERVICE:
        max-attempts: 3
        waitDuration: 500
  timelimiter:
    instances:
      PAYMENT-SERVICE:
        timeoutDuration: 10ms # hoặc để giây thì 5s, dưới giây thì dùng ms 10ms = 0.01s

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 172.18.160.1
    hostname: localhost
    metadata-map:
      weight: 50
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

