spring:
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017/notification-service?authSource=admin
  #      username: root
  #      password: 123456

  config:
    name: notification-service
    import: optional:configserver:http://localhost:8888

  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: guest
  #    password: guest
  #
  #  cloud:
  #    bus:
  #      trace:
  #        enabled: true

  kafka:
    bootstrap-servers: localhost:9094



firebase:
  service-account: "src/main/resources/service-account.json"
