spring:
  application:
    name: POST-SERVICE

  config:
    name: post-service
    import: optional:configserver:http://localhost:8888

  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017/posts?authSource=admin
