spring:
  application:
    name: BOOK-SERVICE

  config:
    import: optional:configserver:http://localhost:8888
    name: book-service

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/book_service
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9094

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    bus:
      trace:
        enabled: true

cloudinary:
  cloud-name: dznef2sae
  api-key: 537285485346489
  api-secret: PHu0HBagBqf1rgfKMSJpSLUh29M

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0 # 100% request được tracking (nếu hệ thống lớn, có thể giảm xuống 0.5)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans