spring:

  config:
    import: optional:configserver:http://localhost:8888
    name: inventory-service

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-service
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9094

management:
  endpoints:
    web:
      exposure:
        include: "*"
