spring:
  config:
    name: order-service
    import: optional:configserver:http://config-server:8888

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://postgres:5432/order_service
  jpa:
    hibernate:
      ddl-auto: update

  #  rabbitmq:
  #    host: rabbitmq
  #    port: 5672
  #    username: guest
  #    password: guest
  #
  #  cloud:
  #    bus:
  #      trace:
  #        enabled: true

  kafka:
    bootstrap-servers: kafka:9092