spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat_service
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: optional:configserver:http://localhost:8888
    name: chat-service


