spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgres://localhost:5432/cart_service

  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: optional:configserver:http://config-server:8888
    name: cart-service

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#  cloud:
#    bus:
#      trace:
#        enabled: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://registry-service:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true