spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/cart_service

  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: optional:configserver:http://localhost:8888
    name: cart-service

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#  cloud:
#    bus:
#      trace:
#        enabled: true