server:
  port: 8087
  servlet:
    context-path: /search
spring:
  application:
    name: SEARCH-SERVICE

  config:
    import: optional:configserver:http://localhost:8888
    name: search-service

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  tracing:
#    sampling:
#      probability: 1.0 # 100% request được tracking (nếu hệ thống lớn, có thể giảm xuống 0.5)
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans