spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lekhanhduc/Spring-Cloud-Config-Server
          clone-on-start: true
          default-label: main
          username: lekhanhduc
          password: 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
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/