spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lekhanhduc/Spring-Cloud-Config-Server
          clone-on-start: true
          default-label: production
          username: lekhanhduc
          password: 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
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/