spring:
  application:
    name: NOTIFICATION-SERVICE

  config:
    name: notification-service
    import: optional:configserver:http://localhost:8888

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#  cloud:
#    bus:
#      trace:
#        enabled: true

  #  data:
#    mongodb:
#      uri: mongodb://localhost:27017/notification-service?authSource=admin
#      username: root
#      password: 123456
  kafka:
    bootstrap-servers: localhost:9094


brevo:
  api-key: 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
  from: lekhanhduccc@gmail.com