spring:
  application:
    name: NOTIFICATION-SERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27017/notification-service?authSource=admin
      username: root
      password: 123456

server:
  port: 8888
  servlet:
    context-path: /notification

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

brevo:
  api-key: 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
  from: lekhanhduccc@gmail.com