spring:
  application:
    name: NOTIFICATION-SERVICE

server:
  port: 8888
  servlet:
    context-path: /notification

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/