server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  application:
    name: PROFILE-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
    name: profile-service
  neo4j:
    authentication:
      username: neo4j
      password: 12345678
    uri: bolt://localhost:7687
  jpa:
    hibernate:
      ddl-auto: update