server:
  port: 8888
spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: ${Uri-Config-Server}
          clone-on-start: true
          default-label: main
          username: ${User-Name-Github}
          password: ${Personal-Access-Token}
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/