spring:
  application:
    name: IDENTITY-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/identity
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  config:
    import: "optional:configserver:http://localhost:8888"

jwt:
  secret-key: ${JWT_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: "*"
